version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db/concept_development
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      - POSTGRES_DB=concept_development
      - POSTGRES_PASSWORD=postgres
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - web
